### ISSUE TITLE
[question] Is JsonAvroConverter thread safe?

### ISSUE THREAD

**Issue by palmerabollo** [allegro/json-avro-converter#1]
Is `JsonAvroConverter` thread safe? Is it safe to reuse the same `JsonAvroConverter` instance in different calls to the `convertToAvro` method? Thank you.

**Comment by druminski** [comment]
Hi,

Thanks for the first issue/question to this lib. `JsonAvroConverter` is thread safe, because under the hood it shares only Jackson `ObjectMapper` which basically is thread safe. Here you can read more about [Jackson thread-safety rule](Jackson thread-safety).

**Comment by palmerabollo** [comment]
Great, thanks!
