### ISSUE TITLE
Function does not exists 'convertToSpecificRecord' in version 0.2.5 (Maven repository)

### ISSUE THREAD

**Issue by jmresendiz** [allegro/json-avro-converter#24]
Hi!
I'm using your excellent contribution, but a have a problem. I like to use a funtion named  'convertToSpecificRecord' (in 'json-avro-converter/converter/src/main/java/tech/allegro/schema/json2avro/converter/JsonAvroConverter.java' ), but, it dont exists in the maven repository. Im using, 

<dependency>
   <groupId>tech.allegro.schema.json2avro</groupId>
   <artifactId>converter</artifactId>
   <version>0.2.5</version>
</dependency>

**Comment by adamdubiel** [comment]
Seems like i never released version with this function. Doing it right now. `0.2.6` should be on Maven Central in few hours.
