### ISSUE TITLE
Support schema type BYTES

### ISSUE THREAD

**Issue by thomasm82** [allegro/json-avro-converter#27]
Currently the method `tech.allegro.schema.json2avro.converter.JsonGenericRecordReader.read(Field, Schema, Object, Deque<String>, boolean)` does not support the Avro type `BYTES`. I am currently working on a project, where this is a requirement, though.

My suggestion would be to support the type `BYTES` by converting a Base64 string to bytes. This is the most natural way I think JSON can represent binary data.

**Comment by adamdubiel** [comment]
Released in 0.2.8.
