### ISSUE TITLE
Generated GenericRecords with Enums can't be written using GenericDatumWriter

### ISSUE THREAD

**Issue by twinlock** [allegro/json-avro-converter#5]
Hey guys, 

I'm using tech.allegro.schema.json2avro:converter:0.2.3 and org.apache.avro:avro:1.8.1 trying to convert some json to avro for some code of mine. I want to use the Java API and since I see no other way to get this to work, I write the generic data out to an avro encoded stream, then read it in through the specific datum reader (i know, my heart aches too). 

Took this example from another bug, but it illustrates it all the same:
```
val schema = """{
               |  "type": "record",
               |  "name": "testSchema",
               |  "fields": [
               |    {
               |      "name": "eventType",
               |      "type": {
               |        "name": "EventType",
               |        "type": "enum",
               |        "symbols": ["user"]
               |      }
               |    }
               |  ]
               |}""".stripMargin

val json = """{"eventType":"user"}"""
val generic = new JsonAvroConverter().convertToAvro(json.getBytes, schema)
val out: ByteArrayOutputStream out = new ByteArrayOutputStream()
val encoder: Encoder = EncoderFactory.get().binaryEncoder(out, null)
val writer: GenericDatumWriter[GenericRecord]  = new GenericDatumWriter(getSchema());
writer.write(generic, encoder)
```
throws
Not an enum: user
org.apache.avro.AvroTypeException: Not an enum: user
    at org.apache.avro.generic.GenericDatumWriter.writeEnum(GenericDatumWriter.java:164)
    at org.apache.avro.generic.GenericDatumWriter.writeWithoutConversion(GenericDatumWriter.java:106)

Dug into the code a bit and found this [line](https://github.com/allegro/json-avro-converter/blob/master/converter/src/main/java/tech/allegro/schema/json2avro/converter/JsonGenericRecordReader.java#L123):
```
 private Object ensureEnum(Schema schema, Object value, Deque<String> path) {
        List<String> symbols = schema.getEnumSymbols();
        if(symbols.contains(value)){
           return value;
        }
        throw enumException(path, symbols.stream().map(String::valueOf).collect(joining(", ")));
    }
```

Problem is that returns a String, not a GenericData.EnumSymbol so when this generic object is read, it throws the aforementioned error.

**Comment by adamdubiel** [comment]
I think we fixed this one in 0.2.4 - could you check it please? Works fine for us.
