### ISSUE TITLE
0.2.11 version not allowing extra attributes in request json

### ISSUE THREAD

**Issue by optimasquad** [allegro/json-avro-converter#71]
We have recently upgraded the library version in our code base from 0.2.9 to 0.2.11 and facing issues after that. 

**Features Deprecated in 0.2.11**

0.2.9 version when the input json contains the extra attributes in the json that are not part of avro were not getting failed and extra attributes were part of the response json

0.2.11 version when the input json contains the extra attributes in the json that are not part of avro are now getting failed and extra attributes were part of the response json The class AvroTypeConverterWithStrictJavaTypeCheck is creating a problem as it check for the fields in the josn showl match the fields in the avro schema. 

Why the upgraded version 0.2.11 is not backward compatible? 

Is there any provision by which in 0.2.11 version can safeguard the failures and work in compatible with 0.2.9?

**Comment by ThomasDangleterre** [comment]
Hello,

I had the same issue. Rollbacking to 2.10 fixed it, so I guess only 2.11 is affected.
